import Head from 'next/head';
import styles from '../styles/Home.module.css';
import NavBar from '../components/NavBar';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PUBG BATTLEGROUNDS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <h2>main content</h2>
      </main>
      <footer className={styles.footer}>
        <h2>footer</h2>
      </footer>
    </div>
  )
}
