import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/Header.js';
import Hero from '../components/Hero';
import About from './about';
import Rewards from './rewards';
import Steps from './steps';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PUBG BATTLEGROUNDS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <Hero/>
        <About/>
        <Rewards/>
        <Steps/>
        <footer className={styles.footer}/>
      </main>
    </div>
  )
}
